### ISSUE TITLE
Docker failing to download new OpenRCT2 0.4.3 assets & unpack them

### ISSUE THREAD

**Issue by solarsparq** [ich777/docker-openrct2-server#2] opened 2023-01-11 04:25 UTC
Hello again,

Thank you for your work on this.  I was re-starting my family's stack of OpenRCT2 Dockers & noticed they attempted to grab the latest release & are all failing in the same way.  It appears to run into permission issues & is unable to finish.  Is OpenRCT2 changing how they release in some way?

I apologize for the formatting on the Docker log, I can't figure out how to easily make it fit into a code/quote block.

Please let me know if you need any more information.  Thank you in advance.

---Ensuring UID: 99 matches user---
---Ensuring GID: 100 matches user---
---Setting umask to 000---
---Checking for optional scripts---
---No optional script found, continuing---
---Taking ownership of data...---
---Starting...---
---Version missmatch, installing v0.4.3!---
/serverdata/serverf   0%[                    ]       0  --.-KB/s               
/serverdata/serverf   0%[                    ] 503.38K  2.17MB/s               
/serverdata/serverf   2%[                    ]   1.19M  2.71MB/s               
/serverdata/serverf   3%[                    ]   1.73M  2.69MB/s               
/serverdata/serverf   4%[                    ]   2.27M  2.69MB/s               
/serverdata/serverf   5%[>                   ]   2.83M  2.69MB/s               
/serverdata/serverf   6%[>                   ]   3.40M  2.70MB/s               
/serverdata/serverf   7%[>                   ]   3.88M  2.66MB/s               
/serverdata/serverf   8%[>                   ]   4.48M  2.69MB/s               
/serverdata/serverf  10%[=>                  ]   5.07M  2.71MB/s               
/serverdata/serverf  11%[=>                  ]   5.55M  2.68MB/s               
/serverdata/serverf  12%[=>                  ]   6.15M  2.71MB/s               
/serverdata/serverf  13%[=>                  ]   6.65M  2.68MB/s               
/serverdata/serverf  14%[=>                  ]   7.23M  2.70MB/s               
/serverdata/serverf  15%[==>                 ]   7.76M  2.69MB/s               
/serverdata/serverf  16%[==>                 ]   8.24M  2.67MB/s    eta 16s    
/serverdata/serverf  17%[==>                 ]   8.79M  2.71MB/s    eta 16s    
/serverdata/serverf  18%[==>                 ]   9.27M  2.66MB/s    eta 16s    
/serverdata/serverf  19%[==>                 ]   9.76M  2.63MB/s    eta 16s    
/serverdata/serverf  20%[===>                ]  10.27M  2.62MB/s    eta 16s    
/serverdata/serverf  21%[===>                ]  10.60M  2.55MB/s    eta 15s    
/serverdata/serverf  21%[===>                ]  10.93M  2.47MB/s    eta 15s    
/serverdata/serverf  22%[===>                ]  11.32M  2.44MB/s    eta 15s    
/serverdata/serverf  23%[===>                ]  11.74M  2.41MB/s    eta 15s    
/serverdata/serverf  24%[===>                ]  12.15M  2.33MB/s    eta 15s    
/serverdata/serverf  25%[====>               ]  12.56M  2.29MB/s    eta 15s    
/serverdata/serverf  25%[====>               ]  12.94M  2.24MB/s    eta 15s    
/serverdata/serverf  26%[====>               ]  13.32M  2.20MB/s    eta 15s    
/serverdata/serverf  27%[====>               ]  13.79M  2.17MB/s    eta 15s    
/serverdata/serverf  28%[====>               ]  14.25M  2.12MB/s    eta 15s    
/serverdata/serverf  29%[====>               ]  14.69M  2.12MB/s    eta 15s    
/serverdata/serverf  30%[=====>              ]  15.09M  2.07MB/s    eta 15s    
/serverdata/serverf  31%[=====>              ]  15.56M  2.06MB/s    eta 15s    
/serverdata/serverf  32%[=====>              ]  16.11M  2.08MB/s    eta 15s    
/serverdata/serverf  33%[=====>              ]  16.71M  2.11MB/s    eta 15s    
/serverdata/serverf  34%[=====>              ]  17.26M  2.14MB/s    eta 14s    
/serverdata/serverf  35%[======>             ]  17.76M  2.20MB/s    eta 14s    
/serverdata/serverf  36%[======>             ]  18.35M  2.29MB/s    eta 14s    
/serverdata/serverf  37%[======>             ]  18.93M  2.35MB/s    eta 14s    
/serverdata/serverf  38%[======>             ]  19.46M  2.37MB/s    eta 14s    
/serverdata/serverf  39%[======>             ]  19.98M  2.42MB/s    eta 12s    
/serverdata/serverf  40%[=======>            ]  20.50M  2.46MB/s    eta 12s    
/serverdata/serverf  42%[=======>            ]  21.12M  2.53MB/s    eta 12s    
/serverdata/serverf  43%[=======>            ]  21.68M  2.58MB/s    eta 12s    
/serverdata/serverf  44%[=======>            ]  22.19M  2.59MB/s    eta 12s    
/serverdata/serverf  45%[========>           ]  22.82M  2.64MB/s    eta 11s    
/serverdata/serverf  46%[========>           ]  23.23M  2.64MB/s    eta 11s    
/serverdata/serverf  47%[========>           ]  23.82M  2.72MB/s    eta 11s    
/serverdata/serverf  48%[========>           ]  24.38M  2.72MB/s    eta 11s    
/serverdata/serverf  49%[========>           ]  24.94M  2.73MB/s    eta 11s    
/serverdata/serverf  50%[=========>          ]  25.50M  2.71MB/s    eta 10s    
/serverdata/serverf  52%[=========>          ]  26.12M  2.75MB/s    eta 10s    
/serverdata/serverf  53%[=========>          ]  26.93M  2.83MB/s    eta 10s    
/serverdata/serverf  55%[==========>         ]  27.75M  2.91MB/s    eta 10s    
/serverdata/serverf  56%[==========>         ]  28.53M  2.97MB/s    eta 10s    
/serverdata/serverf  58%[==========>         ]  29.29M  3.04MB/s    eta 8s     
/serverdata/serverf  59%[==========>         ]  29.96M  3.10MB/s    eta 8s     
/serverdata/serverf  61%[===========>        ]  30.71M  3.15MB/s    eta 8s     
/serverdata/serverf  62%[===========>        ]  31.52M  3.20MB/s    eta 8s     
/serverdata/serverf  64%[===========>        ]  32.18M  3.28MB/s    eta 8s     
/serverdata/serverf  65%[============>       ]  32.83M  3.30MB/s    eta 6s     
/serverdata/serverf  66%[============>       ]  33.46M  3.30MB/s    eta 6s     
/serverdata/serverf  67%[============>       ]  34.02M  3.34MB/s    eta 6s     
/serverdata/serverf  68%[============>       ]  34.55M  3.32MB/s    eta 6s     
/serverdata/serverf  70%[=============>      ]  35.15M  3.33MB/s    eta 6s     
/serverdata/serverf  71%[=============>      ]  35.79M  3.37MB/s    eta 5s     
/serverdata/serverf  72%[=============>      ]  36.33M  3.34MB/s    eta 5s     
/serverdata/serverf  73%[=============>      ]  36.95M  3.32MB/s    eta 5s     
/serverdata/serverf  75%[==============>     ]  37.57M  3.23MB/s    eta 5s     
/serverdata/serverf  76%[==============>     ]  38.15M  3.17MB/s    eta 5s     
/serverdata/serverf  77%[==============>     ]  38.72M  3.10MB/s    eta 4s     
/serverdata/serverf  78%[==============>     ]  39.27M  3.04MB/s    eta 4s     
/serverdata/serverf  79%[==============>     ]  39.82M  2.99MB/s    eta 4s     
/serverdata/serverf  80%[===============>    ]  40.32M  2.92MB/s    eta 4s     
/serverdata/serverf  81%[===============>    ]  40.88M  2.85MB/s    eta 4s     
/serverdata/serverf  82%[===============>    ]  41.40M  2.81MB/s    eta 3s     
/serverdata/serverf  83%[===============>    ]  42.02M  2.80MB/s    eta 3s     
/serverdata/serverf  85%[================>   ]  42.78M  2.85MB/s    eta 3s     
/serverdata/serverf  87%[================>   ]  43.59M  2.95MB/s    eta 3s     
/serverdata/serverf  88%[================>   ]  44.22M  2.98MB/s    eta 3s     
/serverdata/serverf  89%[================>   ]  45.02M  3.03MB/s    eta 2s     
/serverdata/serverf  91%[=================>  ]  45.84M  3.11MB/s    eta 2s     
/serverdata/serverf  93%[=================>  ]  46.70M  3.20MB/s    eta 2s     
/serverdata/serverf  94%[=================>  ]  47.40M  3.22MB/s    eta 2s     
/serverdata/serverf  96%[==================> ]  48.20M  3.31MB/s    eta 2s     
/serverdata/serverf  97%[==================> ]  49.00M  3.36MB/s    eta 0s     
/serverdata/serverf  99%[==================> ]  49.69M  3.38MB/s    eta 0s     
/serverdata/serverf 100%[===================>]  50.08M  3.43MB/s    in 18s     
---Sucessfully downloaded OpenRCT2---
/opt/scripts/start-server.sh: line 71: /serverdata/serverfiles/OPENRCT2-v0.4.3.AppImage: Permission denied
/opt/scripts/start-server.sh: line 72: /serverdata/serverfiles/OPENRCT2-v0.4.3.AppImage: Permission denied
mv: cannot stat '/serverdata/serverfiles/squashfs-root': No such file or directory
find: paths must precede expression: `openrct2installedv0.4.3'
find: possible unquoted pattern after predicate `-name'?
-----------------------------------------
---Newer version of OpenRCT2 available---
---Installed version:  ------------
---Available version: 0.4.3 ------------
-----------------------------------------
---Preparing Server---
---Setting up config.ini---
---Starting Server---
---Loading last autosave file---
/opt/scripts/start-server.sh: line 194: /serverdata/serverfiles/ORCT2/usr/bin/openrct2-cli: No such file or directory
---Ensuring UID: 99 matches user---
usermod: no changes
---Ensuring GID: 100 matches user---
usermod: no changes
---Setting umask to 000---
---Checking for optional scripts---
---No optional script found, continuing---
---Taking ownership of data...---
---Starting...---
---Version missmatch, installing v0.4.3!---**

**Comment by josiah-roberts** [comment] 2023-12-26 02:13
+1, I have a related issue.
```
/opt/scripts/start-server.sh: line 45: /serverdata/serverfiles/OPENRCT2-v0.4.6.AppImage: Permission denied
```

**Comment by ich777** [comment] 2023-12-26 07:19
Thank you for the report, I will look into that shortly and report back.

**Comment by ich777** [comment] 2023-12-26 07:34
Hey both of you @josiah-roberts & @solarsparq 

I can't reproduce this over here, I attached the log from a completely fresh installed server and it is working fine so far:  [OpenRCT_log.txt](https://github.com/ich777/docker-openrct2-server/files/13769595/OpenRCT_log.txt)

Can bot of you look in the server directory if you have a file called `OPENRCT2-v$GAME_VERSION.AppImage` in the directory and if it exists remove this file and restart the container?

From what I can tell the first startup was not successful or it failed during the installation, which should be a rare case and that's what maybe causing this issue.

**Comment by ich777** [comment] 2023-12-28 07:34
@josiah-roberts & @solarsparq any update on this?

**Comment by josiah-roberts** [comment] 2023-12-28 16:58
I went around the problem for the family Christmas RCT session and ran on bare metal. If I encounter any useful info, I'll let you know.

**Comment by ich777** [comment] 2023-12-28 17:08
I can't reproduce that on Unraid and it is working flawlessly on a new instance. If I don't hear back from the other user I'll close this issue in a few days.

However @josiah-roberts I think in your case it was ultimately a permission issue.

**Comment by josiah-roberts** [comment] 2023-12-28 17:20
For the context I can give right now, I spun up a brand new VM in GCP using the container optimized image. I then did a docker run, and encountered that error extracting the AppImage.

I have also had intermittent similar issues on my Unraid server, where the container crashes updating (idk if it was the same step, not at home), but repeatedly re-starting the container eventually made it come up.

That's all I know right now.

**Comment by ich777** [comment] 2023-12-28 17:59
I can only tell you that I‘ve pulled down a fresh copy from the CA App and it was working right OOB.

If you interrupt the first start it could happen what you two are describing.

I‘m not to sure about the permission issue eince I‘ve had some issues in the past with other containers (not on Unraid) where if the wrong UID and GID where similar issues occured.

**Comment by ich777** [comment] 2024-01-04 08:10
Since to no further response and me not being able to reproduce this issue on my Server I'll close this issue, if you have further issues feel free to open up a new issue.

However I've pushed an update to the container since something changed with the GitHub API with the beginning of 2024 which prevented the container from grabbing the version.

**Closed as completed by ich777** 2024-01-04 08:10 UTC
